---
name: "Build & Test"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ğŸ—ï¸ğŸ§ª Build and Test ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Client"
            path: "client"
            platform: macos-latest
          - name: "Client"
            path: "client"
            platform: ubuntu-latest
          - name: "Client"
            path: "client"
            platform: windows-latest
          - name: "Server"
            path: "server"
            platform: macos-latest
          - name: "Server"
            path: "server"
            platform: ubuntu-latest
          - name: "Server"
            path: "server"
            platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: "1.22"
      - name: Build
        run: go build -v ./...
        working-directory: ${{ matrix.path }}
      - name: Test
        run: go test -v ./...
        working-directory: ${{ matrix.path }}
